import casadi as ca
import numpy as np
from abc import ABC, abstractmethod
from typing import Callable, Union
from stable_baselines3.common.base_class import BaseAlgorithm
from environments.utils.funcionesEMS import *
from environments.Data.EMS.EMS_constants import *

class PumpingPolicy(ABC):
    """
    Abstract class for pumping policies.
    """

    def __init__(self, n_crops=1, ):
        self.n_crops = n_crops

    @abstractmethod
    def get_action(self, water_reqs:np.ndarray, observation:np.ndarray) -> np.ndarray:
        """
        Get the action for the given observation.
        :param observation: The observation of the environment.
        :return: The action to be taken.
        """
        pass


class RBPumpingPolicy(PumpingPolicy):
    """
    Rule-based pumping policy.
    """
    def __init__(self, n_crops=1, v_tank_max:float=5.0):
        super().__init__(n_crops)
        self.v_tank_max:float = v_tank_max

    def get_action(self, water_reqs:np.ndarray, observation:np.ndarray) -> np.ndarray:
        
        v_tanks = np.array(observation[0:self.n_crops])
        v_irrs = np.array(observation[self.n_crops:2*self.n_crops])
        assert len(water_reqs) == self.n_crops, "Water requirements and number of crops do not match"
        
        q_irrs = np.clip((water_reqs - v_irrs)*1000/3600, 0, 1)
        q_ps = np.array([q_irrs[idx] if v_tank < self.v_tank_max else 0.0 for idx, v_tank in enumerate(v_tanks)]) 
        return np.concatenate((q_ps, q_irrs)) 
    
class RLPumpingPolicy(PumpingPolicy):
    """Class for the Q_p, Q_irr action space agent"""
    def __init__(self, n_crops: int, rl_policy: BaseAlgorithm, isNormalized: bool = False):
        super().__init__(n_crops)
        self.policy = rl_policy
        self.residual: float = 0.0
        if isNormalized:
            self.transform = generate_t_matrix(n_crops)
        else:
            self.transform = np.eye(4 * n_crops + 5)

    def get_action(self,
                   state: tuple[list[float], list[float], list[float], float, int],
                   v_reqs: Union[list[float], np.ndarray],
                   disturbances) -> tuple[float, list[list]]:
        """Computes the action since the current observation
        disturbances: Tuple of (p_fv, p_load)
        return pbat, [[Q_p, Qirr]]"""
        p_fv = disturbances[0]
        p_load = disturbances[1]
        n_crops = self.n_crops

        v_tanks, v_irrs, drawdowns = state[0], state[1], state[2]

        flattened_state = np.concatenate((v_reqs, v_tanks, v_irrs, drawdowns,
                                          np.array([p_fv, p_load, state[3], self.residual, state[4]])))
        transformed_state = np.matmul(self.transform, flattened_state)
        actions = self.policy.predict(transformed_state, deterministic=True)[0]
        Q_p = actions[0:n_crops]
        P_q_ps = get_p_q_p(Q_p, h_p_const)
        Q_irr = actions[n_crops:]

        for i in range(n_crops):
            if v_reqs[i] < v_irrs[i]:
                Q_irr[i] = 0.0
        
        pumps = [[Q_p[i], Q_irr[i]] for i in range(n_crops)]

        SoE = state[3]
        Pbat, _, self.residual = manage_batteries(SoE, p_fv, p_load, P_q_ps)
        return Pbat, pumps

class MPCPumpingPolicy(PumpingPolicy):
    def __init__(self, n_crops=1, day_instant: int = 0):
        super().__init__(n_crops)

        self.data_length:int = 144
        self.solar_power_data:list = []
        self.domestic_consumption_data:list = []

        self.p_pv_predictor = None
        self.p_load_predictor = None

        self.day_instant:int = day_instant

        #microgrid specs
    
    def get_action(self, water_req, observation):

        current_solar_power = observation[-2]
        current_domestic_consumption = observation[-1]

        if len(self.solar_power_data) < self.data_length:
            self.solar_power_data.append(current_solar_power)
            self.domestic_consumption_data.append(current_domestic_consumption)
        else:
            self.solar_power_data.pop(0)
            self.solar_power_data.append(current_solar_power)
            self.domestic_consumption_data.pop(0)
            self.domestic_consumption_data.append(current_domestic_consumption)

        day_instant = observation[7]

        #create predictions unti the end of the day

        p_pv = self.p_pv_predictor.predict(np.array(self.solar_power_data), 
                                    144-day_instant)  
        p_load = self.p_load_predictor.predict(np.array(self.domestic_consumption_data), 
                                      144-day_instant)
        

def manage_batteries_sym(SoE: ca.SX,
                     P_fv: ca.SX,
                     P_demanded: ca.SX,
                     P_pump: ca.SX) -> tuple[ca.SX, ca.SX]:
    """
    Computes the power to be charged/discharged in the symbolic domain

    :param SoE: State of Energy of the battery [kWh]
    :param P_fv: power generated by the PV panels [kW]
    :param P_demanded: power demanded by the loads [kW]
    :param P_pumps: power demanded by the pump
    :returns: Pbat, next_SoE, E_residual
    """
    E_surplus = ca.SX(0.0)
    E_deficit = ca.SX(0.0)

    P_residual = P_fv - P_demanded - P_pump
    Pbat = ca.if_else(ca.fabs(P_residual) > Pbat_max, ca.fmin(ca.fmax(P_residual, -Pbat_max), Pbat_max), P_residual)
    P_not_used = P_residual - Pbat

    delta_SoE = ca.if_else(Pbat >= 0, Pbat * n_c * (dt / 3600), Pbat / n_d * (dt / 3600))
    next_SoE = SoE + delta_SoE

    E_surplus = ca.if_else(next_SoE > SoE_max, next_SoE - SoE_max, 0)
    E_deficit = ca.if_else(next_SoE < SoE_min, SoE_min - next_SoE, 0)

    next_SoE = ca.fmin(ca.fmax(next_SoE, SoE_min), SoE_max)
    #Pbat = ca.if_else(delta_SoE > 0, ca.fmax(SoE_max - SoE, 0) / (dt / 3600) / n_c, ca.fmin(SoE_min - SoE, 0) * n_d / (dt / 3600))
    Pbat = ca.if_else(next_SoE > SoE_max , ca.fmax(SoE_max - SoE, 0) / (dt / 3600) / n_c, Pbat)
    Pbat = ca.if_else(next_SoE < SoE_min , ca.fmin(SoE_min - SoE, 0) * n_d / (dt / 3600), Pbat)

    E_surplus += ca.if_else(P_not_used > 0, P_not_used * (dt / 3600), 0)
    E_deficit += ca.if_else(P_not_used < 0, -P_not_used / n_d * (dt / 3600), 0)

    E_residual = E_surplus + E_deficit

    return Pbat, E_residual

def drawdown(k: int, dQ: Iterable):  # drawdown of the well
    """
    Computes the drawdown of the well according the theis equation
    :param k: time instant
    :param dQ: delta flow rate [m3/s]
    :return: drawdown
    """
    assert k == len(dQ), "The length of dQ should match the number of temporal k points"
    
    l = np.arange(1, k + 1)
    arg = (r_wells ** 2 * S) / (4 * T * (k - l + 1) * 600)
    sum_ = 0.0
    for i in range(k):
        sum_ += dQ[i] * exp1(arg[i])
    s_val = 1 / (4 * np.pi * T) * sum_
    return s_val

         

        





        





