import casadi as ca
import numpy as np
from abc import ABC, abstractmethod
from typing import Callable, Union
from stable_baselines3.common.base_class import BaseAlgorithm
from environments.utils.funcionesEMS import *
from environments.Data.EMS.EMS_constants import *
from environments.utils.predict_utils import Forecaster

class PumpingPolicy(ABC):
    """
    Abstract class for pumping policies.
    """

    def __init__(self, n_crops=1, ):
        self.n_crops = n_crops

    @abstractmethod
    def get_action(self, water_reqs:np.ndarray, 
                   observation:np.ndarray, 
                   disturbances:np.ndarray) -> np.ndarray[np.float32, int]:
        """
        Get the action for the given observation.
        :param observation: The observation of the environment.
        :return: The action to be taken.
        """
        pass


class RBPumpingPolicy(PumpingPolicy):
    """
    Rule-based pumping policy.
    """
    def __init__(self, n_crops=1, v_tank_max:float=5.0):
        super().__init__(n_crops)
        self.v_tank_max:float = v_tank_max

    def get_action(self, water_reqs:np.ndarray, observation:np.ndarray, disturbances:np.ndarray) -> np.ndarray:
        
        v_tanks = np.array(observation[0:self.n_crops])
        v_irrs = np.array(observation[self.n_crops:2*self.n_crops])
        drawdowns = np.array(observation[2*self.n_crops:3*self.n_crops])
        water_reqs = water_reqs[:1]
        assert len(water_reqs) == self.n_crops, "Water requirements and number of crops do not match"
        
        q_irrs = []
        q_ps = []
        for idx, v_tank in enumerate(v_tanks):
            if 1.0 < v_tank:
                q_irr = np.clip((water_reqs - v_irrs)*1000/600, 0, .5).item()
            if v_tank < Vt_max and np.abs(drawdowns[idx]) < 1.0:
                q_p = q_irr
            else:
                q_p = 0.0
            q_ps.append(q_p)
            q_irrs.append(q_irr)    
        q_ps = np.array(q_ps)
        q_irrs = np.array(q_irrs)
        return np.concatenate((q_ps, q_irrs)) 
    
class RLPumpingPolicy(PumpingPolicy):
    """Class for the Q_p, Q_irr action space agent"""
    def __init__(self, n_crops: int, rl_policy: BaseAlgorithm, isNormalized: bool = False):
        super().__init__(n_crops)
        self.policy = rl_policy
        self.residual: float = 0.0
        if isNormalized:
            self.transform = generate_t_matrix(n_crops)
        else:
            self.transform = np.eye(4 * n_crops + 5)

    def get_action(self, water_reqs:np.ndarray, observation:np.ndarray, disturbances:np.ndarray) -> np.ndarray:
        """Computes the action since the current observation
        disturbances: Tuple of (p_fv, p_load)
        return pbat, [[Q_p, Qirr]]"""
        n_crops = self.n_crops
        

        flattened_state = np.concatenate((water_reqs[0:1], observation, disturbances))
        transformed_state = np.matmul(self.transform, flattened_state)
        actions = self.policy.predict(transformed_state, deterministic=True)[0]


        for i in range(n_crops):
            if water_reqs[i] < observation[1]:
                actions[self.n_crops + i] = 0.0
        
        return actions
        

def manage_batteries_ca(SoE: ca.SX,
                     P_fv: ca.SX,
                     P_demanded: ca.SX,
                     P_pump: ca.SX) -> tuple[ca.SX, ca.SX]:
    """
    Choose the power to re/discharge the batteries and computes the next SoE
    :param SoE: State of Energy of the battery [kWh]
    :param P_fv: power generated by the PV panels [kW]
    :param P_demanded: power demanded by the loads [kW]
    :param P_pumps: list with the power demanded by the pumps
    :returns: Pbat, next_SoE, E_residual
    """
    E_surplus = ca.SX(0.0)
    E_deficit = ca.SX(0.0)

    P_residual = P_fv - P_demanded - P_pump
    Pbat = ca.if_else(ca.fabs(P_residual) > Pbat_max, ca.fmin(ca.fmax(P_residual, -Pbat_max), Pbat_max), P_residual)
    P_not_used = P_residual - Pbat

    delta_SoE = ca.if_else(Pbat >= 0, Pbat * n_c * (dt / 3600), Pbat / n_d * (dt / 3600))
    next_SoE = SoE + delta_SoE

    E_surplus = ca.if_else(next_SoE > SoE_max, next_SoE - SoE_max, 0)
    E_deficit = ca.if_else(next_SoE < SoE_min, SoE_min - next_SoE, 0)

    next_SoE = ca.fmin(ca.fmax(next_SoE, SoE_min), SoE_max)
    #Pbat = ca.if_else(delta_SoE > 0, ca.fmax(SoE_max - SoE, 0) / (dt / 3600) / n_c, ca.fmin(SoE_min - SoE, 0) * n_d / (dt / 3600))
    Pbat = ca.if_else(next_SoE > SoE_max , ca.fmax(SoE_max - SoE, 0) / (dt / 3600) / n_c, Pbat)
    Pbat = ca.if_else(next_SoE < SoE_min , ca.fmin(SoE_min - SoE, 0) * n_d / (dt / 3600), Pbat)

    E_surplus += ca.if_else(P_not_used > 0, P_not_used * (dt / 3600), 0)
    E_deficit += ca.if_else(P_not_used < 0, -P_not_used / n_d * (dt / 3600), 0)

    E_residual = E_surplus + E_deficit

    return Pbat, E_residual

class MPCPumpingPolicy(PumpingPolicy):
    def __init__(self, pv_model:Forecaster, pd_model:Forecaster, days_ahead:int=0):
        super().__init__(n_crops=1)
        
        self.prev_Q = 0.0  # Previous flow rate
        self.pv_model = pv_model
        self.domestic_model = pd_model
        self.ten_min_counter:int = 0
        self.days_ahead = days_ahead


        self.pv:list = None
        self.pd:list = None

        self.pd_predictions:np.ndarray = None

        self.previous_solution:np.ndarray = None

    def init_buffer(self, pv:np.ndarray, pd:np.ndarray):
        """
        Initialize the buffer with the historical data of the PV and PD
        """
        self.pv = pv.tolist()
        self.pd = pd.tolist()
        self.ten_min_counter = 0
        


    def get_predictions(self, p_pv:float, p_d:float, N:int):
        # Define the control horizon

        #update the buffer
        if self.pv is None or self.pd is None:
            raise ValueError("Buffer not initialized. Call init_buffer() with historical data.")
        
        self.pv.append(p_pv)
        self.pv.pop(0)
        
        if self.ten_min_counter % 6 == 0:  # Every 10 minutes
            self.pd.append(p_d)
            self.pd.pop(0)
            # now compute the predictions
            predictions = self.domestic_model.predict(np.array(self.pd), N//6)
            preds = [p_d] * 5
            for value in predictions:
                preds.extend([value] * 6)
            self.pd_predictions = np.array(preds)
        self.ten_min_counter += 1
        
        p_pv_predicted = self.pv_model.predict(np.array(self.pv), N)
        return p_pv_predicted, self.pd_predictions[-N:]
    
    def get_action(self, water_reqs:np.ndarray, observation:np.ndarray, disturbances:np.ndarray) -> np.ndarray:
        water_reqs = water_reqs[:self.days_ahead + 1]
        N = (1 + self.days_ahead) * 144 - int(observation[6])  # Control horizon (144 ten-minute intervals in a day)
        p_pv = disturbances[0]  # PV power
        p_d = disturbances[1]  # Domestic power
    
        # Define optimization variables
        U = ca.SX.sym("U", 2, N)  # Control inputs
        X = ca.SX.sym("X", 5, N + 1)  # States
        K_p = 1.0
        # Define the cost function and constraints
        cost = 0

        p_pv_preds, p_d_preds = self.get_predictions(p_pv, p_d, N)

        v_tank, v_irr, drawdown, soe = observation[0], observation[1], observation[2], observation[4]


        # Initial conditions
        constraints = [(X[0,0] - v_tank),  # v_tanks
                    (X[1,0] - v_irr),   # v_irrs
                    (X[2,0] - drawdown),  # drawdown
                    (X[3,0]- soe), # soe
                    (X[4,0] - self.prev_Q)] # Previous qp
                    

        for j in range(N):
            # Dynamics constraint
            
            constraints.append(X[0,j + 1] - (X[0, j] + (U[0, j]-U[1, j])*dt/1000))  # Vtanks
            constraints.append(
                X[1, j + 1] - ca.if_else(j == 144, (U[1, j] * dt / 1000), (X[1, j] + U[1, j] * dt / 1000))
            )  # Virrs
            constraints.append(X[2,j + 1] - ((1-0.0540)*X[2,j] + 0.0939*U[0,j] - 0.1404*X[4,j])) # Drawdown
            p_bat, e_res = manage_batteries_ca(X[3, j], float(p_pv_preds[j]), float(p_d_preds[j]), K_p*U[0, j])
            constraints.append(X[3,j + 1] - (X[3, j] + p_bat*dt/3600))  # SoE
            constraints.append(X[4,j + 1] - U[0,j])  # Previous qp
            
            # Update 

            constraints.append(X[0,j+1])
            constraints.append(X[1,j+1])
            constraints.append(X[2,j+1])
            constraints.append(X[3,j+1])
            #constraints.append(X[4,j+1])

            constraints.append(U[0,j])
            constraints.append(U[1,j])
            cost += -e_res

        # Define bounds for constraints
        lbg = [0,0,0,0,0]  # Equality constraint for initial condition
        ubg = [0,0,0,0,0]

        for j in range(N):
            # Equality constraints for dynamics
            lbg.extend([0, 0, 0, 0, 0])  # Lower bounds for dynamics
            ubg.extend([0, 0, 0, 0, 0])  # Upper bounds for dynamics

            lbg.extend([1, 0, -1, 20])  # Lower bounds 
            ubg.extend([5, ca.inf, 1, 100])  # Upper bounds 

            # Inequality constraint for U[0, j] >= 0
            lbg.extend([0, 0])  # Lower bound
            ubg.extend([1.0, 1.0])  # No upper bound

        # Final condition (equality constraint)
        for i in range(1, self.days_ahead + 2):
            constraints.append(X[1, N - (i-1)*144] - float(water_reqs[self.days_ahead + 1 - i]))  # Final condition (reference fulfillment)

            lbg.append(0)
            ubg.append(0)


        # Combine decision variables into a single vector
        decision_variables = ca.vertcat(ca.reshape(X, -1, 1), ca.reshape(U, -1, 1))
        # Create the NLP problem
        nlp_control = {
            'x': decision_variables,  # Decision variables
            'f': cost,             # Objective function
            'g': ca.vertcat(*constraints)  # Constraints
        }

        opts = {'ipopt.print_level':0, 'print_time':0}

        # Create the solver
        solver_control = ca.nlpsol('solver_control', 'ipopt', nlp_control, opts)
        #
        if self.previous_solution is not None and N != (1 + self.days_ahead) * 144:
            x0 = self.previous_solution
        else:
            x0 = np.zeros((5 * (N + 1) + 2 * N,))
        solution_control = solver_control(
            x0=x0,  # Initial guess
            lbg=lbg,  # Lower bound on constraints
            ubg=ubg   # Upper bound on constraints
        )

        # Extract the solution for decision variables
        solution_values = solution_control['x']

        state_values = ca.reshape(solution_values[:5 * (N + 1)], (5, N + 1))

        # Extract the cost value
        #solution_cost = solution_control['f']

        # Extract the constraint values
        #solution_constraints = solution_control['g']
        #states = np.array(ca.reshape(solution_values[:5 * (N + 1)], (5, N + 1)))
        actions = ca.reshape(solution_values[5 * (N + 1):], (2, N))

        self.previous_solution = ca.vertcat(ca.reshape(state_values[:, 1:], -1, 1), ca.reshape(actions[:,1:], -1, 1)).toarray()
        action_array = np.array(actions)

        self.prev_Q = action_array[0, 0]  # Update previous flow rate
        return action_array[:,0]


        



         

        





        





