import pandas as pd
from typing import Union, Tuple, Iterable, Any
from environments.Data.EMS.EMS_constants import *

delay = 6 * 6  # 6 hours in 10 minutes intervals

df = pd.read_csv("environments/Data/EMS/CCALAN.csv")
df = df.ffill()

def get_sept_to_jan(df):
    # Convert the date column to datetime
    df = df.copy()
    df['Fecha Hora (YYYY-MM-DD HH:MM)'] = pd.to_datetime(df['Fecha Hora (YYYY-MM-DD HH:MM)'])
    # Extract month
    months = df['Fecha Hora (YYYY-MM-DD HH:MM)'].dt.month
    # September (9) to January (1), including both
    mask = (months >= 9) | (months <= 1)
    return df[mask]

df_sept_to_jan = get_sept_to_jan(df)

# Enumerate how many seasons are in the data (September to January is one "season" per year)
def get_seasons(df):
    # Group by year, where season is from September (year N) to January (year N+1)
    df = df.copy()
    df['year'] = df['Fecha Hora (YYYY-MM-DD HH:MM)'].dt.year
    df['month'] = df['Fecha Hora (YYYY-MM-DD HH:MM)'].dt.month
    # For months Sep-Dec, season is the current year; for Jan, season is previous year
    df['season'] = np.where(df['month'] == 1, df['year'] - 1, df['year'])
    seasons = df['season'].unique()
    return np.sort(seasons)

seasons = get_seasons(df_sept_to_jan)

# Function to select data from a certain season
def select_season(df, season):
    df = df.copy()
    df['year'] = df['Fecha Hora (YYYY-MM-DD HH:MM)'].dt.year
    df['month'] = df['Fecha Hora (YYYY-MM-DD HH:MM)'].dt.month
    df['season'] = np.where(df['month'] == 1, df['year'] - 1, df['year'])
    return df[df['season'] == season]

# Number of seasons: 8
# Seasons: [2013 2014 2015 2016 2017 2018 2019 2021]

def get_demand() -> np.ndarray[Any, np.dtype[np.floating]]:
    """
    Read the demand data from the csv file and returns it as a numpy array
    :return: Demand data as a numpy array [kWh]
    """

    hourly_demand = np.genfromtxt("environments/Data/EMS/consumption.csv", delimiter=',')
    s_hourly_demand = hourly_demand.shape
    demand = np.zeros((s_hourly_demand[0], s_hourly_demand[1] * 6))
    for i in range(s_hourly_demand[0]):
        for j in range(s_hourly_demand[1]):
            demand[i, j * 6:(j + 1) * 6] = hourly_demand[i, j]
    demand = demand.flatten()
    return demand

def get_demand_2() -> np.ndarray[Any, np.dtype[np.floating]]:
    """
    Read the demand data from the csv file and returns it as a numpy array
    :return: Demand data as a numpy array [kWh]
    """

    hourly_demand = np.genfromtxt("environments/Data/EMS/consumption.csv", delimiter=',')
    return hourly_demand.flatten()


def solar_power(rad: Union[float, np.ndarray[Any, np.dtype[np.floating]]], 
                temp: Union[float, np.ndarray[Any, np.dtype[np.floating]]]) -> Union[float, np.ndarray[Any, np.dtype[np.floating]]]:
    """
    Computes the solar power in kW given the radiation in W/m2 and the temperature in C.

    :parameter rad: Radiation in W/m2
    :parameter temp: Temperature in °C
    :return: Solar power in kW

    """
    Pn = 81#90
    a_fv = -.0045
    Tn = 25
    T_cell = temp + rad / 800 * (Tn - 20)
    return (Pn * rad / 1000.) * (1 + a_fv * (T_cell - Tn))



def manage_batteries(SoE: float,
                     P_fv: float,
                     P_demanded: float,
                     P_pumps: Iterable[float]) -> Tuple[float, float, float]:
    """
    Choose the power to re/discharge the batteries and computes the next SoE
    :param SoE: State of Energy of the battery [kWh]
    :param P_fv: power generated by the PV panels [kW]
    :param P_demanded: power demanded by the loads [kW]
    :param P_pumps: list with the power demanded by the pumps
    :returns: Pbat, next_SoE, E_residual
    """
    E_surplus = 0.0
    E_deficit = 0.0
    P_pump = sum(P_pumps)

    P_residual = P_fv - P_demanded - P_pump
    if not -Pbat_max <= P_residual <= Pbat_max:  # The surplus is out of the power bounds of the battery
        Pbat = np.clip(P_residual, -Pbat_max, Pbat_max)  # positive for surplus, negative for deficit
        P_not_used = P_residual - Pbat  # positive for surplus, negative for deficit. In case of negative value is P not available

    else:
        P_not_used = 0
        Pbat = P_residual

    delta_SoE = np.max([Pbat, 0]) * n_c * (dt / 3600) + np.min([Pbat, 0]) / n_d * (dt / 3600)  # [kWh]
    next_SoE = SoE + delta_SoE

    if SoE_min <= next_SoE <= SoE_max:  # The recharge is done immediately
        Pbat = Pbat
    else:  # The re/discharge is done but there is a surplus/deficit of energy
        E_surplus = next_SoE - SoE_max if next_SoE > SoE_max else 0
        E_deficit = next_SoE - SoE_min if next_SoE < SoE_min else 0

        next_SoE = np.clip(next_SoE, SoE_min, SoE_max)
        
        Pbat = np.max([SoE_max - SoE, 0]) / (dt / 3600) / n_c if next_SoE > SoE_max else Pbat
        
        Pbat = np.min([SoE_min - SoE, 0]) * n_d / (dt / 3600) if next_SoE < SoE_min else Pbat
        # Pbat = np.max([SoE_max - SoE, 0]) / (dt / 3600) / n_c + np.min([SoE_min - SoE, 0]) * n_d / (dt / 3600)

    E_surplus = E_surplus + P_not_used * (dt / 3600) if P_not_used > 0 else E_surplus
    E_deficit = E_deficit + P_not_used / n_d * (dt / 3600) if P_not_used < 0 else E_deficit

    E_residual = E_surplus + E_deficit

    return Pbat, next_SoE, E_residual

def generate_t_matrix(n_crops:int, v_ref_max:float=5) -> np.ndarray[Any, np.dtype[np.floating]]:
    """
    Generates the transformation matrix for the observation vector
    returns: t_matrix, the transformation matrix
    v_ref, v_tank, v_irr, drawdowns, p_ps, soe, k, e_res p_pv, p_load
    """
    t_matrix = np.zeros((5*n_crops+4, 4*n_crops+6), dtype=np.float32)
    for i in range(n_crops):
        t_matrix[i, i] = 1/v_ref_max
        t_matrix[i+n_crops, i+n_crops] = 1/Vt_max
        t_matrix[i+2*n_crops, i+2*n_crops] = 1/v_ref_max
        t_matrix[i+3*n_crops, i+3*n_crops] = 1.0 # drawdowns
        t_matrix[i+4*n_crops, i+4*n_crops] = 1.0 # p_pump

        t_matrix[5*n_crops+3, i+4*n_crops] = -1.0/(max_power_sun-max_power_d) # -p_pump
    t_matrix[5*n_crops, 5*n_crops] = 1/SoE_max #soe
    t_matrix[5*n_crops+1, 5*n_crops+1] = 1.0 # e residual
    t_matrix[5*n_crops+2, 5*n_crops+2] = 1/143 # 
    
    #lets continue with the other components
    t_matrix[5*n_crops+3, 5*n_crops+3] = 1.0/(max_power_sun-max_power_d) # p_pv
    t_matrix[5*n_crops+3, 5*n_crops+4] = -1.0/(max_power_sun-max_power_d) # p_l 

    return t_matrix

def get_p_q_p(q_p: Union[float, np.ndarray[Any, np.dtype[np.floating]]], 
              h_p: float) -> Union[float, np.ndarray[Any, np.dtype[np.floating]]]:
    """Water pump power [kW]
    :param q_p: flow rate [l/s]
    :param h_p: height [m]
    :return: power [kW]"""
    if type(q_p) == float:
        q_p = np.array([q_p])
    q_p = q_p * 1e-3 # l/s -> m3/s
    P_Q_p_ = B_p * q_p * h_p
    P_Q_p_ = P_Q_p_ * 1e-3  # W -> kW
    return P_Q_p_

