import pandas as pd
from typing import Union, Tuple, Iterable
from environments.Data.EMS.EMS_constants import *

delay = 6 * 6  # 6 hours in 10 minutes intervals


def get_demand() -> np.ndarray:
    """
    Read the demand data from the csv file and returns it as a numpy array
    :return: Demand data as a numpy array [kWh]
    """

    hourly_demand = np.genfromtxt("environments/Data/EMS/consumption.csv", delimiter=',')
    s_hourly_demand = hourly_demand.shape
    demand = np.zeros((s_hourly_demand[0], s_hourly_demand[1] * 6))
    for i in range(s_hourly_demand[0]):
        for j in range(s_hourly_demand[1]):
            demand[i, j * 6:(j + 1) * 6] = hourly_demand[i, j]
    demand = demand.flatten()
    return demand


def get_temperatura(season: str = 'ver') -> np.ndarray:
    """
    Read the temperature data from the csv file and returns it as a numpy array

    :param season: 'ver' for summer and 'inv' for winter
    :return: Temperature data as a numpy array
    """
    if season == 'ver':
        file_path = "environments/Data/EMS/data_temp_ver.csv"
    else:
        file_path = "environments/Data/EMS/data_temp_inv.csv"
    temperatura = pd.read_csv(file_path)
    temperatura = temperatura.interpolate().values.flatten()
    return temperatura[delay:]


def get_rad(season: str = 'ver') -> np.ndarray:
    """
    Read the radiation data from the csv file and returns it as a numpy array

    :param season: 'ver' for summer and 'inv' for winter
    :return: Radiation data as a numpy array

    """
    if season == 'ver':
        file_path = "environments/Data/EMS/data_rad_ver.csv"
    else:
        file_path = "environments/Data/EMS/data_rad_inv.csv"

    rad = pd.read_csv(file_path)
    rad = rad.values.flatten()
    return rad[delay:]


def get_ref() -> np.ndarray:
    """Read the references data from the csv file and returns it as a numpy array"""
    refs = pd.read_csv('environments/Data/EMS/v_refs.csv')
    refs = refs.values.flatten()
    return refs


def solar_power(rad: Union[float, np.ndarray], temp: Union[float, np.ndarray]) -> Union[float, np.ndarray]:
    """
    Computes the solar power in kW given the radiation in W/m2 and the temperature in C.

    :parameter rad: Radiation in W/m2
    :parameter temp: Temperature in °C
    :return: Solar power in kW

    """
    Pn = 90
    a_fv = -.0045
    Tn = 25
    T_cell = temp + rad / 800 * (Tn - 20)
    return (Pn * rad / 1000.) * (1 + a_fv * (T_cell - Tn))


def follow_ref_rew_1(s, a, s_next) -> np.ndarray:
    """
    Reward function for the follow reference task
    :param s: current state
    :param a: action
    :param s_next: next state
    :return: reward
    """
    reward = 0

    if np.abs(s[0] - s[1]) > np.abs(s[0] - s_next[1]):
        reward = reward + 1

    elif s[0] < s[1] < s_next[1]:
        reward = reward - 2

    tank_reward = 0  # (s_next[3])*.8 if s_next[3] <= 5 else 0

    reward = reward + tank_reward

    # unfeasible action penalty
    if s[3] <= 1 and a[0] > 0:
        reward = reward - 5

    if s[3] >= 5 and a[1] > 0:
        reward = reward - 5

    return np.array([reward], dtype=np.float32)


def manage_batteries(SoE: float,
                     P_fv: float,
                     P_demanded: float,
                     P_pumps: Iterable[float]) -> Tuple[float, float, float]:
    """
    Choose the power to re/discharge the batteries and computes the next SoE
    :param SoE: State of Energy of the battery [kWh]
    :param P_fv: power generated by the PV panels [kW]
    :param P_demanded: power demanded by the loads [kW]
    :param P_pumps: list with the power demanded by the pumps
    :returns: Pbat, next_SoE, E_residual
    """
    E_surplus = 0.0
    E_deficit = 0.0
    P_pump = sum(P_pumps)

    P_residual = P_fv - P_demanded - P_pump
    if not -Pbat_max <= P_residual <= Pbat_max:  # The surplus is out of the power bounds of the battery
        Pbat = np.clip(P_residual, -Pbat_max, Pbat_max)  # positive for surplus, negative for deficit
        P_not_used = P_residual - Pbat  # positive for surplus, negative for deficit. In case of negative value is P not available

    else:
        P_not_used = 0
        Pbat = P_residual

    delta_SoE = np.max([Pbat, 0]) * n_c * (dt / 3600) + np.min([Pbat, 0]) / n_d * (dt / 3600)  # [kWh]
    next_SoE = SoE + delta_SoE

    if SoE_min <= next_SoE <= SoE_max:  # The recharge is done immediately
        Pbat = Pbat
    else:  # The re/discharge is done but there is a surplus/deficit of energy
        E_surplus = next_SoE - SoE_max if next_SoE > SoE_max else 0
        E_deficit = next_SoE - SoE_min if next_SoE < SoE_min else 0

        next_SoE = np.clip(next_SoE, SoE_min, SoE_max)
        if delta_SoE > 0:
            Pbat = np.max([SoE_max - SoE, 0]) / (dt / 3600) / n_c
        else:
            Pbat = np.min([SoE_min - SoE, 0]) * n_d / (dt / 3600)
        # Pbat = np.max([SoE_max - SoE, 0]) / (dt / 3600) / n_c + np.min([SoE_min - SoE, 0]) * n_d / (dt / 3600)

    E_surplus = E_surplus + P_not_used * (dt / 3600) if P_not_used > 0 else E_surplus
    E_deficit = E_deficit + P_not_used / n_d * (dt / 3600) if P_not_used < 0 else E_deficit

    E_residual = E_surplus + E_deficit

    return Pbat, next_SoE, E_residual

def generate_t_matrix(n_crops:int, v_ref_max:float=5) -> np.ndarray:
    """
    Generates the transformation matrix for the observation vector
    returns: t_matrix, the transformation matrix
    """
    t_matrix = np.zeros((4*n_crops+4, 4*n_crops+5), dtype=np.float32)
    for i in range(n_crops):
        t_matrix[i, i] = 1/v_ref_max
        t_matrix[i+n_crops, i+n_crops] = 1/Vt_max
        t_matrix[i+2*n_crops, i+2*n_crops] = 1/v_ref_max
        t_matrix[i + 3 * n_crops, i + 3 * n_crops] = 1.0
        # drawdowns
    t_matrix[4*n_crops, 4*n_crops] = 1/(max_power_sun-max_power_d)
    # demanded power is combined with the power from the pvs array
    t_matrix[4*n_crops, 4*n_crops+1] = - 1/(max_power_sun - max_power_d)
    t_matrix[4*n_crops+1, 4*n_crops+2] = 1/SoE_max
    #residual energy
    t_matrix[4*n_crops+2, 4*n_crops+3] = 1
    t_matrix[4*n_crops+3, 4*n_crops+4] = 1/144

    return t_matrix

def get_p_q_p(q_p: Union[float, np.ndarray], h_p: float) -> np.ndarray:
    """Water pump power [kW]
    :param q_p: flow rate [l/s]
    :param h_p: height [m]
    :return: power [kW]"""
    if type(q_p) == float:
        q_p = np.array([q_p])
    q_p = q_p * 1e-3 # l/s -> m3/s
    P_Q_p_ = B_p * q_p * h_p
    P_Q_p_ = P_Q_p_ * 1e-3  # W -> kW
    return P_Q_p_

